<a href="https://colab.research.google.com/github/alanmartin-dev/Taller_Practica_NumPy/blob/main/Ejercicios_AlanEspa%C3%B1a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Taller de Numpy
##Autor: Alan España

##Módulo 1. Listas

In [1]:
# Creación
valores = [5, 15, 25, 35, 45]
mezcla = ['a', 2, 4.5, False]
vacía = []
rango = list(range(2, 12))

# Acceso
print(valores[0])
print(valores[-1])
print(valores[-2])

# Slicing
print(valores[1:4])
print(valores[:2])
print(valores[3:])
print(valores[::2])
print(valores[::-1])

# Métodos
valores.append(55)
valores.insert(1, 99)
valores.remove(99)
ultimo = valores.pop()
print(len(valores))

5
45
35
[15, 25, 35]
[5, 15]
[35, 45]
[5, 25, 45]
[45, 35, 25, 15, 5]
5


#1.1 List comprehension

In [2]:
# Básica
cubos = [x**3 for x in range(1, 6)]
print(cubos)
# Con filtro
impares = [x for x in range(1, 15) if x % 2 != 0]
print(impares)
# Con bucle tradicional equivalente
lista = []
for x in range(1, 15):
    if x % 2 != 0:
        lista.append(x)
print(lista)
# Anidada
tabla = [[i + j for j in range(1, 4)] for i in range(1, 4)]
print (tabla)
# Transformación
nombres = ['Ana', 'JUAN', 'Pedro']
print(nombres)
minus = [n.lower() for n in nombres]
print(minus)

[1, 8, 27, 64, 125]
[1, 3, 5, 7, 9, 11, 13]
[1, 3, 5, 7, 9, 11, 13]
[[2, 3, 4], [3, 4, 5], [4, 5, 6]]
['Ana', 'JUAN', 'Pedro']
['ana', 'juan', 'pedro']


#1.2 Tuplas

In [3]:
punto = (10, 20)
forma = (64, 64, 1)
unitaria = (7,)
no_tupla = (7)

print(forma[0])
print(forma[-1])

x, y = punto
alto, ancho, canal = forma

import numpy as np
B = np.zeros((2, 3))
print(B.shape)

64
1
(2, 3)


## 1.3 Diccionarios

In [ ]:
persona = {
    'nombre': 'Luis',
    'edad': 30,
    'hobbies': ['leer', 'fútbol'],
    'activo': False
}

print(persona['nombre'])
print(persona.get('ciudad', 'Desconocido'))

persona['edad'] = 31
persona['pais'] = 'Ecuador'

for k, v in persona.items():
    print(k, v)

cuadrados = {x: x**2 for x in range(2, 7)}

if 'nombre' in persona:
    print("Existe")

Luis
Desconocido
nombre Luis
edad 31
hobbies ['leer', 'fútbol']
activo False
pais Ecuador
Existe


## 1.4 Funciones

In [ ]:
def despedir(nombre):
    return f'Adiós, {nombre}'

def elevar(base, exp=3):
    return base ** exp

print(elevar(2))
print(elevar(2, 4))

def extremos(lista):
    return min(lista), max(lista)

a, b = extremos([10, 5, 20, 8])

triple = lambda x: x * 3
print(triple(4))

nums = [3, 6, 1, 9]
orden = sorted(nums, key=lambda x: x)

cuad = list(map(lambda x: x**2, nums))
may = list(filter(lambda x: x > 4, nums))

8
16
12


#Módulo 2 - NumPy

##2.1 Arrays desde listas

In [ ]:
v = np.array([5, 10, 15, 20])
M = np.array([[2,4,6],[8,10,12]])

mix = np.array([1, 2.5, 3])
print(mix.dtype)

f32 = np.array([1,2,3], dtype=np.float32)
bools = np.array([1,0,1], dtype=bool)

float64


##2.2 Funciones de creación

In [4]:
ceros = np.zeros((2,3))
unos = np.ones((3,2))

I = np.eye(3)

a = np.arange(1, 9, 2)
b = np.linspace(0, 5, 6)

np.random.seed(10)
uni = np.random.rand(2,3)
norm = np.random.randn(2,3)
ent = np.random.randint(5, 15, size=(2,2))

###2.3 Atributos

In [5]:
A = np.random.randint(0,50,(2,3,2))

print(A.shape)
print(A.ndim)
print(A.size)
print(A.dtype)
print(A.itemsize)
print(A.nbytes)

v = np.array([1,2,3])
M = np.array([[1,2,3]])
print(v.shape)
print(M.shape)

(2, 3, 2)
3
12
int64
8
96
(3,)
(1, 3)


#MÓDULO 3 - Indexing, Slicing y Transformaciones de Forma


##3.1 Indexing

In [6]:
M = np.array([[2,4,6],[8,10,12],[14,16,18]])

print(M[0,1])
print(M[2,2])
print(M[-1,-1])

print(M[1,:])
print(M[:,2])

4
18
18
[ 8 10 12]
[ 6 12 18]


##3.2 Slicing


In [8]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

sub = A[0:2,0:2]

print(A[:2,:])
print(A[1:,1:])

vista = A[0,:]
copia = A[0,:].copy()

vista[0] = 100

[[1 2 3]
 [4 5 6]]
[[5 6]
 [8 9]]


##3.3 Máscaras


In [7]:
datos = np.array([3, 7, 12, 5, 20])

mask = datos > 10
print(datos[mask])

rango = datos[(datos >= 5) & (datos <= 15)]

copia = datos.copy()
copia[copia < 5] = 0

res = np.where(datos > 10, datos, -1)

[12 20]


##3.4 Fancy Indexing


In [9]:
M = np.array([[1,2],[3,4],[5,6]])

print(M[[0,2]])
print(M[[2,1,0]])
print(M[:,[1,0]])

[[1 2]
 [5 6]]
[[5 6]
 [3 4]
 [1 2]]
[[2 1]
 [4 3]
 [6 5]]


##3.5 Reshape


In [10]:
v = np.arange(8)

M = v.reshape(2,4)
auto = v.reshape(-1,2)

flat = M.flatten()
rav = M.ravel()

col = np.array([1,2,3]).reshape(-1,1)
fil = np.array([1,2,3]).reshape(1,-1)

#MÓDULO 4 - Operaciones Numéricas y Manipulación de Datos



##4.1 Operaciones

In [11]:
a = np.array([2,4,6])
b = np.array([1,3,5])

print(a + b)
print(a * b)
print(a ** 2)

print(a + 10)

[ 3  7 11]
[ 2 12 30]
[ 4 16 36]
[12 14 16]


##4.2 Broadcasting


In [12]:
v = np.array([1,2,3])
M = np.ones((2,3))

print(M + v)

col = np.array([[1],[2]])
fil = np.array([10,20,30])

print(col + fil)

[[2. 3. 4.]
 [2. 3. 4.]]
[[11 21 31]
 [12 22 32]]


##4.3 ufuncs


In [ ]:
v = np.array([-1, -4, 9])

print(np.abs(v))
print(np.sqrt(np.abs(v)))
print(np.square(v))

pos = np.array([1,2,3])
print(np.log(pos))
print(np.exp(pos))

##4.4 Reducciones


In [13]:
M = np.array([[1,2,3],[4,5,6]])

print(M.sum())
print(M.mean())

print(M.sum(axis=0))
print(M.sum(axis=1))

print(M.max(axis=1))

21
3.5
[5 7 9]
[ 6 15]
[3 6]


##4.5 Concatenación


In [15]:
A = np.array([[1,2]])
B = np.array([[3,4]])

print(np.concatenate([A,B], axis=0))
print(np.concatenate([A,B], axis=1))

v1 = np.array([1,2])
v2 = np.array([3,4])

print(np.vstack([v1,v2]))
print(np.hstack([v1,v2]))

[[1 2]
 [3 4]]
[[1 2 3 4]]
[[1 2]
 [3 4]]
[1 2 3 4]


##4.6 Ordenamiento


In [14]:
v = np.array([4,1,3,2])

print(np.sort(v))

idx = np.argsort(v)
print(v[idx])

datos = np.array([0,2,0,5])
print(np.where(datos > 0))

u, c = np.unique([1,2,2,3,3,3], return_counts=True)

[1 2 3 4]
[1 2 3 4]
(array([1, 3]),)
