<a href="https://colab.research.google.com/github/alanmartin-dev/Taller_Practica_NumPy/blob/main/Modulos_NumPy_AlanEspa%C3%B1a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctica Módulo 1


Autor: Alan España

##Ejercicio 1: Crea una lista con los múltiplos de 7 entre 1 y 100 usando comprehension.

In [ ]:

multiplos_de_siete = [x for x in range (1,101) if x % 7 == 0]
print(multiplos_de_siete)

[7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98]


##Ejercicio 2: Dado el diccionario datos = {'a':10, 'b':25, 'c':7, 'd':18}

In [ ]:
datos = {'a':10, 'b':25, 'c':7, 'd':18}

###a) Crea una lista con las claves cuyo valor sea mayor a 12.

In [ ]:
new_list = []
for clave, valor in datos.items():
  if valor > 12:
   new_list = new_list + [clave]
print(new_list)

['b', 'd']


###b) Crea un nuevo diccionario con esas claves y sus valores al cuadrado.

In [ ]:
nuevo_diccionario = {}
for clave, valor in datos.items():
  if valor > 12:
    nuevo_diccionario[clave] = valor ** 2
print(nuevo_diccionario)

{'b': 625, 'd': 324}


##Ejercicio 3: Define una función 'resumen(lista)' que retorne un diccionario con: longitud, suma, promedio, mínimo y máximo de la lista.

In [ ]:
def resumen(lista):
  return {
     'logitud': len(lista),
      'Suma ': sum(lista),
      'Promedio ':sum(lista)/len(lista),
      'Minimo ': min(lista),
      'Maximo': max(lista)}

resumen = resumen ([1,4,25,53,6])
print(resumen)

{'logitud': 5, 'Suma ': 89, 'Promedio ': 17.8, 'Minimo ': 1, 'Maximo': 53}


##Ejercicio 4: Usa map() para aplicar la función potencia(x, 3) a la lista [1,2,3,4,5].

In [ ]:
def potencia(x,n):
  return x ** n

lista = [1,2,3,4,5]
resultado = list(map(lambda x: potencia (x,3),lista))

print (resultado)

[1, 8, 27, 64, 125]


#Práctica Módulo 2

##Ejercicio 1: Crea los siguientes arrays y verifica sus atributos (shape, dtype, ndim)

####a) Vector con enteros del 1 al 20.

In [ ]:
import numpy as np
vec_a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
#print(vec_a)
print(vec_a.shape)
print(vec_a.dtype)
print(vec_a.ndim)

(20,)
int64
1


###b) Matriz de ceros de 5 filas y 3 columnas.

In [ ]:
matrix_zeros = np.zeros((5,3))
#print(matrix_zeros)
print(matrix_zeros.shape)
print(matrix_zeros.dtype)
print(matrix_zeros.ndim)

(5, 3)
float64
2


###c) 10 puntos igualmente espaciados entre -1 y 1 con linspace.

In [ ]:
fun_linspace = np.linspace(-1,1,10)
#print(fun_linspace)
print(fun_linspace.shape)
print(fun_linspace.dtype)
print(fun_linspace.ndim)

(10,)
float64
1


##Ejercicio 2: Con np.random.seed(99) crea una matriz 4×4 de enteros entre 0 y 50. Imprime: shape, dtype, tamaño en bytes (nbytes) y el elemento [2,3].


In [ ]:
np.random.seed(99)
matrix_random = np.random.randint(0,50,(4,4))
print(matrix_random)
print(matrix_random.shape)
print(matrix_random.dtype)
print(matrix_random.nbytes)
print(matrix_random[2,3])

[[ 1 35 40  9]
 [40 18  4  5]
 [ 1 23 35 49]
 [ 1 48 29 38]]
(4, 4)
int64
128
49


##Ejercicio 3: ¿Cuál es la diferencia de dtype entre np.array([1,2,3]) y np.array([1.0,2.0,3.0])? Verifica con código.

In [ ]:
test_1 = np.array([1,2,3])
test_2 = np.array([1.0,2.0,3.0])
print(test_1.dtype)
print(test_2.dtype)

int64
float64


##Ejercicio 4: Crea una matriz identidad 5×5 y verifica que la suma de su diagonal es igual a 5 (usa np.trace()).

In [ ]:
matrix_identity = np.identity(5)
print(matrix_identity)
print(np.trace(matrix_identity))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
5.0


#Práctica Módulo 3

##Ejercicio 1: Dado A = np.arange(1, 26).reshape(5, 5)

In [ ]:
A = np.arange(1, 26).reshape(5, 5)
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


###a) Extrae la sub-matriz de las 3 últimas filas y las 3 primeras columnas.

In [ ]:
print(A[2:5, 0:3])

[[11 12 13]
 [16 17 18]
 [21 22 23]]


###b) Extrae la segunda columna completa.

In [ ]:
print(A[:,1])

[ 2  7 12 17 22]


###c) Extrae los elementos de los ángulos (esquinas) de la matriz

In [ ]:
print(A[[0,0,4,4],[0,4,0,4]])

[ 1  5 21 25]


##Ejercicio 2: Con la misma matriz A:

####a) Crea una máscara booleana para los valores mayores a 12.

In [ ]:
mask = A >12
print(mask)

[[False False False False False]
 [False False False False False]
 [False False  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


###b) Reemplaza esos valores por -1 en una copia del array.

In [ ]:
copy_A = A.copy()
copy_A[mask] = -1
print(copy_A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


###c) Usa np.where para reemplazar impares por 0 y mantener los pares

In [ ]:
condicion = np.where(A % 2 != 0, 0, A )
print(condicion)

[[ 0  2  0  4  0]
 [ 6  0  8  0 10]
 [ 0 12  0 14  0]
 [16  0 18  0 20]
 [ 0 22  0 24  0]]


##Ejercicio 3: Crea un vector de 24 elementos con arange(24).

In [ ]:
vector = np.arange(24)
print(vector)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


##Reorganízalo en:
###(a) matriz 6×4

In [ ]:
vector.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

####(b) tensor 2×3×4

In [ ]:
vector.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

###(c) vector fila 1×24

In [ ]:
vector.reshape(1,24)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

##Ejercicio 4: Demuestra la diferencia vista (Ravel) vs. copia (Flat): modifica un elemento en un slice y verifica que el array original también cambia.

In [ ]:
flat = A.flatten()
rav = A.ravel()
flat[0] = 99
print(A[0, 0]) # 1 → flatten no modifica el original
rav[0] = 77
print(A[0, 0]) # 77 → ravel SÍ modifica el original (es vista)

1
77


#Práctica Módulo 4

##Ejercicio 1: Crea una matriz 5×4 de enteros aleatorios entre 1 y 100 (seed=7).

In [ ]:
np.random.seed(7)
matrix = np.random.randint(1, 101, size=(5, 4))
print(matrix)

[[48 69 26 68]
 [84 24 93 58]
 [15 24 73 90]
 [43 91  9 40]
 [69 49  8 45]]


###a) Calcula la media, máximo y mínimo de cada columna.

In [ ]:
print(np.mean(matrix, axis=0))
print(np.max(matrix, axis=0))
print(np.min(matrix, axis=0))

[51.8 51.4 41.8 60.2]
[84 91 93 90]
[15 24  8 40]


###b) Calcula la suma acumulada de la primera fila.

In [ ]:
print(np.cumsum(matrix[0]))

[ 48 117 143 211]


####c) Normaliza la matriz para que cada columna tenga valores entre 0 y 1.
###Fórmula: (x - min_col) / (max_col - min_col)

In [ ]:
min_col = np.min(matrix, axis = 0)
max_col = np.max(matrix, axis = 0)
normalized_matrix = (matrix - min_col)/(max_col - min_col)
print(normalized_matrix)

[[0.47826087 0.67164179 0.21176471 0.56      ]
 [1.         0.         1.         0.36      ]
 [0.         0.         0.76470588 1.        ]
 [0.4057971  1.         0.01176471 0.        ]
 [0.7826087  0.37313433 0.         0.1       ]]


###Ejercicio 2: Usando broadcasting:

###a) Crea un vector fila [1,2,3,4] y un vector columna [[10],[20],[30]].

In [ ]:
vector=np.array([1,2,3,4])
vector_col=np.array([[10],[20],[30]])

print(vector)
print(vector_col)

[1 2 3 4]
[[10]
 [20]
 [30]]


###b) Suma ambos vectores y explica el shape del resultado.

In [ ]:
print(vector+vector_col)

##Ejercicio 3: Con el array de notas y nombres del ejemplo de argsort:

In [ ]:

nombres = np.array(['Carlos','Ana','Diana','Pedro','Eva','Luis'])
notas = np.array([75, 92, 88, 61, 95, 78])

###a) ¿Cuántos estudiantes tienen nota mayor al promedio? (usa máscara booleana)

In [ ]:
promedio = np.mean(notas)
mask = notas > promedio
print(np.sum(mask))

3


###b) Imprime solo los nombres de esos estudiantes.

In [ ]:
print(np.array(nombres[mask]))

['Ana' 'Diana' 'Eva']


###Ejercicio 4: Crea dos matrices 3×4 y concaténalas vertical y horizontalmente. Luego divide el resultado vertical en 3 partes iguales con vsplit.

In [6]:
matrix_1 = np.random.randint(1,101, size=(3, 4))
matrix_2 = np.random.randint(1,101, size=(3, 4))

print("Matriz vertical: \n ", np.concatenate((matrix_1, matrix_2), axis=0))
print("Matriz horizontal: \n ",np.concatenate((matrix_1, matrix_2), axis=1))

vsplit_fun = np.vsplit(np.concatenate((matrix_1, matrix_2), axis=0), 3)
print("Este es el resultado con vsplit: \n ", vsplit_fun)

Matriz vertical: 
  [[44 47 12 86]
 [30 23 37 22]
 [92 79 68 26]
 [95 81 20  8]
 [82 59 14 33]
 [47 85 81 96]]
Matriz horizontal: 
  [[44 47 12 86 95 81 20  8]
 [30 23 37 22 82 59 14 33]
 [92 79 68 26 47 85 81 96]]
Este es el resultado con vsplit: 
  [array([[44, 47, 12, 86],
       [30, 23, 37, 22]]), array([[92, 79, 68, 26],
       [95, 81, 20,  8]]), array([[82, 59, 14, 33],
       [47, 85, 81, 96]])]
